name: replambda-server
version: 0.1.0.0
license: MIT
author: leonardo3130
maintainer: leonardopo313@gmail.com
category: Language

library:
  source-dirs: Interpreter
  exposed-modules:
    - Syntax
    - Lexer
    - Parser
    - Utils
    - Alpha
    - Beta
  dependencies:
    - base >=4.18 && <5
    - aeson
    - text

executables:
  replambda-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.18 && <5
      - replambda-server
      - scotty
      - aeson
      - text
      - wai
      - wai-extra
      - wai-cors
      - warp
